language: smalltalk
sudo: false

os:
  - linux

addons:
  ssh_known_hosts: ccmi.fit.cvut.cz

env:
  - ARTIFACT_DIR=openponk-uml-image-$TRAVIS_BUILD_NUMBER

smalltalk:
  - Pharo-6.1

cache:
  directories:
    - $SMALLTALK_CI_BUILD_BASE/pharo-local/package-cache

before_install:
  - openssl aes-256-cbc -K $encrypted_5f9336d727bf_key -iv $encrypted_5f9336d727bf_iv -in .ssh/id_uml_travis.enc -out .ssh/id_uml_travis -d
  - chmod 0400 .ssh/id_openponk_travis
  - eval $(ssh-agent -s)
  - ssh-add .ssh/id_openponk_travis

after_success:
  - ./scripts/copy-image.sh $SMALLTALK_CI_IMAGE $ARTIFACT_DIR/openponk
  - ./scripts/mark-image.sh $ARTIFACT_DIR/openponk

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh
