language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
#  - osx

addons:
  apt:
    packages:
      - libcairo2:i386 # install cairo for Roassal

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-5.0
