language: smalltalk
sudo: false

os:
  - linux

env:
  global:
    - ARTIFACT_DIR=openponk-uml-image-$TRAVIS_BUILD_NUMBER

smalltalk:
  - Pharo32-7.0
  - Pharo64-7.0
  - Pharo64-8.0

cache:
  directories:
    - $SMALLTALK_CI_BUILD_BASE/pharo-local/package-cache
