private - contents
directedAssociationIconContents
	"Private - Method generated with the content of the file File @ D:\OpenPonk\icons\uml\directedAssociation.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw
SFlzAAAG7AAABuwBHnU4NQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA
AADnSURBVDiNY2CgB/A+/F/Q+/B/QWxyLMQY8PcHw1QoMwpdjomQZq89/30YGBiuMTAwXPLY
+z+QJAMC9v8X+M/AYMnAwHCEgYHhBON/Bgv3Hf+FiDbg11+Gqn9/GHph/N//GdoYWRhKiDLA
a89/n/8MDMd2ejC+g4ntcWX8+P8/w1HPPf8D8BrgsP8/z38GBpvtLowb0OV2ujJuZWBgsHDY
/58HpwEHHBm/vBJgqMXlulcCDLUHHBm/4PXCWRPG38TIEYxGQmDgDYAnZY/d/x1wKWJkYjD4
/4/hAtku+P+P4QIHC3YDKAYABoVHXkJDbNUAAAAASUVORK5CYII='