private - contents
literalIconContents
	"Private - Method generated with the content of the file File @ D:\OpenPonk\icons\uml\literal.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw
SFlzAAAG7AAABuwBHnU4NQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA
AABZSURBVDiNY2AYnsBz9/84933/9YlRy4RDNI7xH4MB+QaQAEYNGAwGMGIT9Nz7f8///wyc
TAwM9+AKGRmmb3VmPIaulgWrsf8YFjExMCghC/1lYPhCoWNpBADt2xHuYm6+EwAAAABJRU5E
rkJggg=='