private - contents
packageIconContents
	"Private - Method generated with the content of the file File @ D:\OpenPonk\icons\uml\package.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw
SFlzAAAG7AAABuwBHnU4NQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA
AABkSURBVDiNY2AYaMDIwMDA4Ln3/wHGfwwHcCn6z8TgsN2Z0QGnKV67/zfgswWfPBMBFxIE
EC/s+f+A4T/DAwIKDyDzUbxFyAvYAEwPxV4YNYAKBrAwMEDilNSo/M/E4ECp5dQBALRhHivV
PnSaAAAAAElFTkSuQmCC'