"
I am a specific stereotypes label that explicitly ensures the standard `<<stereotype>>` keyword is displayed above a Stereotype definition's name in a profile diagram.
"
Class {
	#name : 'OPUmlStereotypeOfStereotypeLabel',
	#superclass : 'OPUmlStereotypesLabel',
	#category : 'OpenPonk-ClassEditor-DiagramElements',
	#package : 'OpenPonk-ClassEditor',
	#tag : 'DiagramElements'
}

{ #category : 'accessing' }
OPUmlStereotypeOfStereotypeLabel >> stereotypeNames [

	^ #( stereotype )
]
