"
I am a Commander menu group that organizes context menu commands related to toggling and configuring end labels on UML relationships.
"
Class {
	#name : 'OPUmlEndLabelsRoassalShapeMenuGroup',
	#superclass : 'CmdMenuGroup',
	#category : 'OpenPonk-ClassEditor-Commands-RoassalShape',
	#package : 'OpenPonk-ClassEditor',
	#tag : 'Commands-RoassalShape'
}

{ #category : 'accessing' }
OPUmlEndLabelsRoassalShapeMenuGroup >> name [

	^ 'Association end labels'
]
