"
A stereotype label ensuring the standard <<stereotype>> keyword is rendered above a Stereotype definition name in profile diagrams.
"
Class {
	#name : 'OPUmlStereotypeOfStereotypeLabel',
	#superclass : 'OPUmlStereotypesLabel',
	#category : 'OpenPonk-ClassEditor-DiagramElements',
	#package : 'OpenPonk-ClassEditor',
	#tag : 'DiagramElements'
}

{ #category : 'accessing' }
OPUmlStereotypeOfStereotypeLabel >> stereotypeNames [

	^ #( stereotype )
]
