"
I am a specific stereotypes label that explicitly ensures the standard `<<enumeration>>` keyword is displayed above an Enumeration's name.
"
Class {
	#name : 'OPUmlEnumerationStereotypeLabel',
	#superclass : 'OPUmlStereotypesLabel',
	#category : 'OpenPonk-ClassEditor-DiagramElements',
	#package : 'OpenPonk-ClassEditor',
	#tag : 'DiagramElements'
}

{ #category : 'accessing' }
OPUmlEnumerationStereotypeLabel >> stereotypeNames [

	^ #( enumeration )
]
