"
A stereotype label ensuring the standard <<enumeration>> keyword is displayed above the enumeration name.
"
Class {
	#name : 'OPUmlEnumerationStereotypeLabel',
	#superclass : 'OPUmlStereotypesLabel',
	#category : 'OpenPonk-ClassEditor-DiagramElements',
	#package : 'OpenPonk-ClassEditor',
	#tag : 'DiagramElements'
}

{ #category : 'accessing' }
OPUmlEnumerationStereotypeLabel >> stereotypeNames [

	^ #( enumeration )
]
