accessing
iconMapping
	^ {OPUMLProfile -> OPUmlIcons profileIcon.
	OPUMLPackage -> OPUmlIcons packageIcon.
	OPUMLModel -> OPUmlIcons modelIcon.
	OPUMLClass -> OPUmlIcons classIcon.
	OPUMLDataType -> OPUmlIcons dataTypeIcon.
	OPUMLPrimitiveType -> OPUmlIcons primitiveIcon.
	OPUMLEnumeration -> OPUmlIcons enumIcon.
	OPUMLEnumerationLiteral -> OPUmlIcons literalIcon.
	OPUMLProperty -> OPUmlIcons attributeIcon.
	OPUMLOperation -> OPUmlIcons operationIcon.
	OPUMLConstraint -> OPUmlIcons constraintIcon.
	OPUMLAssociation -> OPUmlIcons directedAssociationIcon.
	OPUMLExtension -> OPUmlIcons extensionIcon.
	OPUMLGeneralization -> OPUmlIcons generalizationIcon.
	OPUMLComment -> OPUmlIcons commentIcon.
	Object -> OPUmlIcons unknownIcon}