"
I store metadata for the OpenPonk-ClassEditor-Plugins package. This package contains integrations, extensions, and specific plugin implementations that enhance the core OpenPonk UML Class Diagram editor environment.
"
Class {
	#name : 'ManifestOpenPonkClassEditorPlugins',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-ClassEditor-Plugins-Manifest',
	#package : 'OpenPonk-ClassEditor-Plugins',
	#tag : 'Manifest'
}
