private - contents
generalizationIconContents
	"Private - Method generated with the content of the file File @ /home/peter/prog/dynacase/git/class-editor/assets/icons/generalization.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QAAAAAAAD5Q7t/AAAA
CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wcVEwo5QdECTAAAABl0RVh0Q29tbWVudABD
cmVhdGVkIHdpdGggR0lNUFeBDhcAAABCSURBVDjLY2AYKuA/LgkmYjT///8fpyGMRGqGKGZk
xNDDSKxmXIYwkqIZmyGMpAYaCd6nXizgBRQbwEKCn0cBDgAAodwVB1P8KwgAAAAASUVORK5C
YII='