SystemOrganization addCategory: #'DynaCASE-ClassEditor'!
SystemOrganization addCategory: 'DynaCASE-ClassEditor-Controllers'!
SystemOrganization addCategory: 'DynaCASE-ClassEditor-Examples'!
SystemOrganization addCategory: 'DynaCASE-ClassEditor-Layouting'!
SystemOrganization addCategory: 'DynaCASE-ClassEditor-Plugin'!
SystemOrganization addCategory: 'DynaCASE-ClassEditor-Support'!
SystemOrganization addCategory: 'DynaCASE-ClassEditor-Tests'!
SystemOrganization addCategory: 'DynaCASE-ClassEditor-Windows'!
