SystemOrganization addCategory: #'OpenPonk-ClassEditor'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Controllers'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Controllers-Tests'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Examples'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Forms'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Layouting'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Plugin'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Profiles'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Shapes'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Tests'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Tests - UI'!
SystemOrganization addCategory: 'OpenPonk-ClassEditor-Windows'!
